version: "3"
services:
  node-app:
    build: .
  mongo:
    image: mongo

    environment:
      - MONGO_INITDB_ROOT_USERNAME=den-docker
      - MONGO_INITDB_ROOT_PASSWORD=den123
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
